config/routes.rb
Rails.application.routes.draw do
  devise_for :travellers
  
  resources :journey, only: [:index, :create, :show, :new]
  resources :waypoints, only: [:create, :destroy]
  resources :trip, only: [:index]
  resources :flights, only: [:index, :new]

  root to: "welcome#index"
end

app/models/airport.rb
class Airport < ActiveRecord::Base

  geocoded_by :lnglat

  private
  def lnglat
    "#{self.longitude}, #{self.latitude}"
  end 
end

app/models/flight.rb
class Flight < Journey

  has_one :flight_plan
  accepts_nested_attributes_for :flight_plan

end

app/models/flight_plan.rb
class FlightPlan < ActiveRecord::Base

  # after_create do
  #   Resque.new << GeocodeAirportCode.new
  # end

  validates :start_airport, :end_airport, presence: true

  belongs_to :flight
  belongs_to :nearest_observation, :foreign_key => 'observation_id', :class_name => "Observation"
  belongs_to :start_airport, :foreign_key => 'start_airport_id', :class_name => "Airport"
  belongs_to :end_airport, :foreign_key => 'end_airport_id', :class_name => "Airport"

  before_validation do
    self.start_airport = find_nearest_airport start_city, start_country
    self.end_airport = find_nearest_airport end_city, end_country
  end

  before_save do
    if self.flight
      self.price = calc_price
      if self.flight && self.flight.waypoints.count < 2
        self.flight.waypoints << create_wp(start_airport)
        self.flight.waypoints << create_wp(end_airport)
      end
      self.nearest_observation = find_nearest_observation
      self.bearing = find_bearing
    end
    self.total_distance = calc_distance
  end

  def get_headwind
    (Math.cos(get_heading_difference) * self.nearest_observation.wind_speed).round
  end

  private
  def find_nearest_airport city, country
    Airport.near(([city, country].join ", "), 500).order("distance").first
  end

  def create_wp airport
    Waypoint.create(name: airport.name, 
    latitude: airport.longitude, longitude: airport.latitude)
  end

  def calc_distance
    (self.start_airport.distance_to self.end_airport).round(0)
  end

  def calc_price
    ((self.flight.passengers) * (5 * (Math.sqrt(calc_distance*2) + 8))).round(2)
  end

  def find_nearest_observation
    Observation.near(self.start_airport, 100).order("distance").first
  end

  def find_bearing
    self.start_airport.bearing_to(self.end_airport)
  end

  def get_heading_difference
    heading_difference = (self.bearing - self.nearest_observation.wind_direction).abs
    heading_difference = heading_difference * (Math::PI / 180)
  end


end

app/models/journey.rb
class Journey < ActiveRecord::Base

  belongs_to :traveller 
  has_many :waypoints, -> { order("position ASC") }

end

app/models/observation.rb
class Observation < ActiveRecord::Base

  geocoded_by :lnglat

  private
  def lnglat
    "#{self.longitude}, #{self.latitude}"
  end 

end

app/models/traveller.rb
class Traveller < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :journeys
  has_many :flights

end

app/models/waypoint.rb
class Waypoint < ActiveRecord::Base

  belongs_to :journey
  acts_as_list scope: :journey

  reverse_geocoded_by :longitude, :latitude do |obj,results|
    if geo = results.first
      obj.name    = [geo.street_address, geo.city].join(", ")
    end
  end

  after_validation :check_if_needs_to_geocode

  private

  def check_if_needs_to_geocode
    reverse_geocode if name == nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @flights = current_traveller.flights
  end

  def new
    @flight = Flight.new
    @flight.flight_plan = FlightPlan.new
  end

end

app/controllers/journey_controller.rb
class JourneyController < ApplicationController

  def new
    @journey = Journey.new()
  end

  def show
    @journey = Journey.find(params[:id])
    redirect_to trip_index_path if @journey.traveller != current_traveller
    @waypoints = @journey.waypoints
  end

  def index
    @journeys = current_traveller.journeys.where(type: nil)
  end

  def create
    if current_traveller.journeys << create_from_params
      redirect_to journey_path(current_traveller.journeys.last)
    else
      render text: "Unable to create journey"
    end
  end

  private
  def allowed_params
    params.permit(journey: [:name], flight: [:name, :passengers, flight_plan_attributes: [:start_city, :end_city, :start_country, :end_country]])
  end

  def create_from_params
    allowed_params.keys[0].titleize.constantize.create(allowed_params.values[0])
  end

end

app/controllers/trip_controller.rb
class TripController < ApplicationController

  def index
  end

end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController

  def destroy
    Waypoint.find(params[:id]).destroy
    render nothing: true
  end

  def create
    @journey = Journey.find(params[:journey]) 
    @journey.waypoints << Waypoint.create(
      latitude: params[:latitude],
      longitude: params[:longitude]
    )
    @waypoints = @journey.waypoints
    render @waypoints
  end

  private
  def allowed_params
    params.require(:waypoint).permit(:latitude, :logitude)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # def add_javascript(*files)
  #   content_for(:head) { javascript_include_tag(*files) }
  # end

end

app/views/flights/index.html.haml
-if @flights.length > 1
  %ul
  - @flights.each do |j|
    %li.journey{class: "large-border-radius"}= link_to j.name, journey_path(j)
-else
  %h3 You have no flights yet.

= link_to "New flight", new_flight_path

app/views/flights/new.html.haml
= form_for @flight, url: journey_index_path do |f|
  = f.label :name
  = f.text_field :name

  = f.label :passengers
  = f.select :passengers, options_for_select(1..5)

  = f.fields_for :flight_plan do |plan|
    = plan.label :start_city
    = plan.text_field :start_city, placeholder: "Swansea"

    = plan.label :start_country
    = plan.text_field :start_country, placeholder: "UK"

    = plan.label :end_city
    = plan.text_field :end_city, placeholder: "Dusseldorf"

    = plan.label :end_country
    = plan.text_field :end_country, placeholder: "Germany"

  = f.submit

app/views/journey/_load_markers.html.erb
<script>
  $(document).ready(
    function() {
    <% if @waypoints.count > 0 %>
      map = new JourneyMap(<%= "#{@waypoints.first.latitude}, #{@waypoints.first.longitude}"%>, 9)
      map.drawMap('#map-canvas')
      <% @waypoints.each do |waypoint| %> 
        var markerObj = new google.maps.LatLng(<%= "#{waypoint.longitude}, #{waypoint.latitude}"%>)
        map.addMarker("<%= waypoint.name %>", markerObj, false)
        map.LatLngList.push(markerObj)
        map.fitView(map.LatLngList)
      <% end %>
    <% else %>
      map = new JourneyMap(51.5072, 0.1275, 10)
      map.drawMap('#map-canvas')
    <% end %>
  });
</script>

app/views/journey/_weather_info.html.haml
#weather-info
  - @obs = @journey.flight_plan.nearest_observation
  %ul
    %li= ("The nearest weather station is #{@obs.name.titleize}").html_safe 
    %li= ("Wind #{@obs.wind_direction}&deg; at #{@obs.wind_speed}mph").html_safe
    %li= ("Flight bearing #{@journey.flight_plan.bearing}&deg;").html_safe
    %li= ("Headwind: #{@journey.flight_plan.get_headwind}mph")

app/views/journey/index.html.haml
-if @journeys.length > 0
  %ul
  - @journeys.each do |j|
    %li.journey{class: "large-border-radius"}= link_to j.name, journey_path(j)
-else
  %h3 You have no journeys yet.

= link_to "New journey", new_journey_path

app/views/journey/new.html.haml
= form_for @journey, url: journey_index_path do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/journey/show.html.haml
= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBwGmEeg9OKIjaWiPE5-GnPR75Y1KXm14g"
= content_for(:head) { render partial: "journey/load_markers" } 
%h2#journey-name= @journey.name
-if @journey.type == "Flight"
  %h3#journey-itinery= "#{@journey.flight_plan.start_airport.iata} to #{@journey.flight_plan.end_airport.iata}" 
  #price 
    Price:
    = ("&pound;#{@journey.flight_plan.price} for #{@journey.passengers} passengers").html_safe
  #total_distance 
    Total distance:
    = "#{@journey.flight_plan.total_distance}M"
  = render partial: "weather_info"
#map-canvas{:data => {journeyID: @journey.id}, class: "block-red-border med-light-shadow tiny-border-radius"}
.waypoint-list
  = render @journey.waypoints.order(position: :asc)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StrataPlan</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>

<header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <nav class="large-border-radius-bottom">
    <ul>
      <li><%= link_to((image_tag "logo.png", id: "logo-main"), root_path) %></li>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "My trips", trip_index_path if traveller_signed_in? %></li>
      <li>
        <menu class="sessions" type="list">
            <li><%= link_to "Register", new_traveller_registration_path %></li>
            <% if current_traveller %>
              <li><%= link_to "Sign out", destroy_traveller_session_path, method: "DELETE" %></li>
            <% else %>
              <li><%= link_to "Sign in", new_traveller_session_path %></li>
            <% end %>
        </menu>
      </li>
  </nav>
</header>

<body>
  <div id="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/trip/index.html.haml
%ol
  %li=link_to "My journeys", journey_index_path
  %li=link_to "My flights", flights_path

app/views/waypoints/_waypoint.html.haml
.waypoint{id: waypoint.id, :data => { position: waypoint.position, longitude: waypoint.longitude, latitude: waypoint.latitude }, class: "large-border-radius med-light-shadow"}
  %h3= waypoint.name
  = image_tag "delete.png", class: "delete-button", id: waypoint.id

app/views/welcome/index.html.erb
<div id="bg_overlay"></div>
<%= video_tag "bokeh.mp4", controls: false, autobuffer: true, autoplay: true, id: :bg_video, loop: true %>
<main class="main-home">
  StrataPlan is a demo of what can be achieved in 10 days. It has:
  <ul>
    <li>Google maps integration</li>
    <li>MetOffice integration</li>
    <li>AJAX</li>
    <li>Encapsulated, object oriented JS</li>
    <li>Dynamic route calculations</li>
    <li>Extensive use of geocoder</li>
    <li>Single-table inheritance</li>
    <li>Scheduled tasks</li>
    <li>97% code coverage (1:0.7)</li>
    <li>Mocked HTTP requests</li>
  </ul>
  <div><%= link_to "View on github", "https://github.com/dansteele/strata-plan"%></div>
</main>